name: Deploy on DigitalOcean

on: workflow_dispatch

# on:
#   push:
#     branches: [main]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repo
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /root/rooster-backend
            pm2 stop rooster
            git pull origin main
            npm install
            pm2 start rooster